# Generated by Django 3.0.2 on 2020-01-14 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time1', models.CharField(max_length=200)),
                ('time2', models.CharField(max_length=200)),
                ('data_hora', models.CharField(max_length=200)),
                ('gols_time1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gols_time2', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_time1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gols_time2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to='bolao.Jogo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
